version: '3.8'

services:
  webapp:
  
    build:
      dockerfile: src/Dockerfile
      context: .
   
    container_name: webapp

    command: uvicorn src.app.main:app --reload  --host webapp --port 8000
    ports:
      - 8000:8000

    volumes:
      - .:/usr/src/app
    
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file:
      - .env
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
  
volumes:
  pgdbdata: null


