"""initial

Revision ID: 36273714e678
Revises: 
Create Date: 2023-10-15 23:39:30.977020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36273714e678"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.String(length=1000), nullable=False),
        sa.Column("answer_text", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_answer_text"), "questions", ["answer_text"], unique=False
    )
    op.create_index(
        op.f("ix_questions_created_at"), "questions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    op.create_index(
        op.f("ix_questions_question_text"), "questions", ["question_text"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_question_text"), table_name="questions")
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_created_at"), table_name="questions")
    op.drop_index(op.f("ix_questions_answer_text"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
